language: node_js
node_js:
  - "8"

cache:
  yarn: true
  directories:
    - "node_modules"

before_install:
  - npm i -g yarn

install:
   - yarn install

jobs:
  include:
    - stage: 'lint'
      script: yarn run lint
    - state: 'test'
      script: yarn run test
    - stage: 'build'
      script: yarn build
